// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: community.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getCommunityDetailByID = `-- name: GetCommunityDetailByID :one
SELECT community_id as id, community_name as name, introduction , create_time FROM ` + "`" + `community` + "`" + ` WHERE community_id = ?
`

type GetCommunityDetailByIDRow struct {
	ID           uint64         `json:"id"`
	Name         string         `json:"name"`
	Introduction sql.NullString `json:"introduction"`
	CreateTime   time.Time      `json:"create_time"`
}

func (q *Queries) GetCommunityDetailByID(ctx context.Context, communityID uint64) (GetCommunityDetailByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommunityDetailByID, communityID)
	var i GetCommunityDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Introduction,
		&i.CreateTime,
	)
	return i, err
}

const getCommunityList = `-- name: GetCommunityList :many
SELECT community_id as id, community_name as name FROM ` + "`" + `community` + "`" + `
`

type GetCommunityListRow struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetCommunityList(ctx context.Context) ([]GetCommunityListRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommunityList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommunityListRow
	for rows.Next() {
		var i GetCommunityListRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
