// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Community struct {
	ID          uint64 `json:"id"`
	CommunityID uint64 `json:"community_id"`
	// 社区名称
	CommunityName string `json:"community_name"`
	// 社区描述
	Introduction sql.NullString `json:"introduction"`
	// 创建时间
	CreateTime time.Time `json:"create_time"`
	// 更新时间
	UpdateTime time.Time `json:"update_time"`
}

// 帖子表
type Post struct {
	ID       uint64 `json:"id"`
	PostID   uint64 `json:"post_id"`
	AuthorID uint64 `json:"author_id"`
	// 所属社区ID
	CommunityID uint64 `json:"community_id"`
	// 帖子标题
	Title string `json:"title"`
	// 帖子内容
	Content sql.NullString `json:"content"`
	// 帖子状态
	Status int8 `json:"status"`
	// 创建时间
	CreateTime time.Time `json:"create_time"`
	// 更新时间
	UpdateTime time.Time `json:"update_time"`
}

// 用户表
type User struct {
	ID     uint64 `json:"id"`
	UserID int64  `json:"user_id"`
	// 用户名
	Username string `json:"username"`
	// 密码
	Password string `json:"password"`
	// 邮箱
	Email string `json:"email"`
	// 性别 0-未知 1-男 2-女
	Gender bool `json:"gender"`
	// 创建时间
	CreateTime time.Time `json:"create_time"`
	// 更新时间
	UpdateTime time.Time `json:"update_time"`
}
