// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO ` + "`" + `post` + "`" + ` (post_id, author_id, community_id, title, content, create_time, update_time) VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreatePostParams struct {
	PostID      uint64         `json:"post_id"`
	AuthorID    uint64         `json:"author_id"`
	CommunityID uint64         `json:"community_id"`
	Title       string         `json:"title"`
	Content     sql.NullString `json:"content"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.PostID,
		arg.AuthorID,
		arg.CommunityID,
		arg.Title,
		arg.Content,
	)
	return err
}

const getPostDetailByID = `-- name: GetPostDetailByID :one
SELECT post_id as id, author_id, community_id, title, status, content, create_time FROM ` + "`" + `post` + "`" + ` WHERE post_id = ?
`

type GetPostDetailByIDRow struct {
	ID          uint64         `json:"id"`
	AuthorID    uint64         `json:"author_id"`
	CommunityID uint64         `json:"community_id"`
	Title       string         `json:"title"`
	Status      int8           `json:"status"`
	Content     sql.NullString `json:"content"`
	CreateTime  time.Time      `json:"create_time"`
}

func (q *Queries) GetPostDetailByID(ctx context.Context, postID uint64) (GetPostDetailByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPostDetailByID, postID)
	var i GetPostDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CommunityID,
		&i.Title,
		&i.Status,
		&i.Content,
		&i.CreateTime,
	)
	return i, err
}

const getPostListByIDs = `-- name: GetPostListByIDs :many

SELECT post_id, title, content, author_id, community_id, create_time 
FROM post 
WHERE FIND_IN_SET(post_id, ?) 
ORDER BY FIND_IN_SET(post_id, ?)
`

type GetPostListByIDsParams struct {
	FINDINSET   string `json:"FIND_IN_SET"`
	FINDINSET_2 string `json:"FIND_IN_SET_2"`
}

type GetPostListByIDsRow struct {
	PostID      uint64         `json:"post_id"`
	Title       string         `json:"title"`
	Content     sql.NullString `json:"content"`
	AuthorID    uint64         `json:"author_id"`
	CommunityID uint64         `json:"community_id"`
	CreateTime  time.Time      `json:"create_time"`
}

// 根据给定的id列表查询帖子数据
func (q *Queries) GetPostListByIDs(ctx context.Context, arg GetPostListByIDsParams) ([]GetPostListByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostListByIDs, arg.FINDINSET, arg.FINDINSET_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostListByIDsRow
	for rows.Next() {
		var i GetPostListByIDsRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Content,
			&i.AuthorID,
			&i.CommunityID,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostListWithDetails = `-- name: GetPostListWithDetails :many
SELECT 
  p.post_id as id, 
  p.author_id, 
  u.username as author_name,
  p.community_id, 
  c.community_name,
  p.title, 
  p.content, 
  p.status,
  p.create_time
FROM ` + "`" + `post` + "`" + ` p
LEFT JOIN ` + "`" + `user` + "`" + ` u ON p.author_id = u.user_id
LEFT JOIN ` + "`" + `community` + "`" + ` c ON p.community_id = c.community_id
ORDER BY p.create_time DESC
LIMIT ?,?
`

type GetPostListWithDetailsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

type GetPostListWithDetailsRow struct {
	ID            uint64         `json:"id"`
	AuthorID      uint64         `json:"author_id"`
	AuthorName    sql.NullString `json:"author_name"`
	CommunityID   uint64         `json:"community_id"`
	CommunityName sql.NullString `json:"community_name"`
	Title         string         `json:"title"`
	Content       sql.NullString `json:"content"`
	Status        int8           `json:"status"`
	CreateTime    time.Time      `json:"create_time"`
}

func (q *Queries) GetPostListWithDetails(ctx context.Context, arg GetPostListWithDetailsParams) ([]GetPostListWithDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostListWithDetails, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostListWithDetailsRow
	for rows.Next() {
		var i GetPostListWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.AuthorName,
			&i.CommunityID,
			&i.CommunityName,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.CreateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
