// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO ` + "`" + `user` + "`" + ` (user_id, username, password, email, gender, create_time, update_time) VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`

type CreateUserParams struct {
	UserID   int64  `json:"user_id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Gender   bool   `json:"gender"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.Gender,
	)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM ` + "`" + `user` + "`" + ` WHERE id = ?
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT id, user_id, username, password, email, gender, create_time, update_time FROM ` + "`" + `user` + "`" + ` WHERE user_id = ?
`

func (q *Queries) GetUserByUserID(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserID, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Gender,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, user_id, username, password, email, gender, create_time, update_time FROM ` + "`" + `user` + "`" + ` WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Gender,
		&i.CreateTime,
		&i.UpdateTime,
	)
	return i, err
}

const updateUserNameByID = `-- name: UpdateUserNameByID :exec
UPDATE ` + "`" + `user` + "`" + ` SET username = ? and update_time = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateUserNameByIDParams struct {
	Username string `json:"username"`
	ID       uint64 `json:"id"`
}

func (q *Queries) UpdateUserNameByID(ctx context.Context, arg UpdateUserNameByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateUserNameByID, arg.Username, arg.ID)
	return err
}
